node {
    def example = "Brixy"
    stage('test Variable'){
        echo "this is an ${example}"
    }
    stage('test'){
        git "https://github.com/tbatty7/web-service.git"
    }
    stage('build'){
        sh "chmod a=rx ./gradlew"
        sh "ls -l"
        sh "./gradlew build"
    }
    stage('Push to PCF'){
        withCredentials([usernamePassword(credentialsId: 'PCF_Credentials', passwordVariable: 'pcf_password', usernameVariable: 'pcf_user')]) {
            sh "cf login -a api.run.pivotal.io -u ${env.pcf_user} -p '${env.pcf_password}'" +
                    " -o Jess-Tim -s development"
            sh "cf push -p build/libs/artifact-id-web-service-0.0.1-SNAPSHOT.jar"
        }
    }
}